### ISSUE TITLE
cxx_init_const, cxx_assign_const and scalar_value_mutator mutations dont show correctly in the mutant viewer

### ISSUE THREAD

**Issue by tbarry2** [tpugh/mutation-viewer#1]

**Comment by tpugh** [comment]
@tbarry2 thank you for bringing up this issue, it does seem as though Mull struggles to put the constant in the correct location or even replaces the entire line with test value 42. If there is a combination of constants or variable values that you can replace it with (even if mull did not generate it)  to make the change an equivalent mutant  you can submit that portion of code with your corrections in finds folder and for the spreadsheet put a *  in the ID entry.

the * will represent self corrected, altered to find equivalent mutant.
